# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonzoCsvExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monzo_id', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('local_amount', models.FloatField()),
                ('local_currency', models.CharField(max_length=3)),
                ('category', models.CharField(max_length=20)),
                ('emoji', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('receipt', models.CharField(max_length=200)),
            ],
        ),
    ]
